config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #homepage
  get '/', to: 'sessions#index', as: 'root'
  #login form
  get '/login', to: 'sessions#new', as:'login'
  #adds user_id to the session
  post '/', to: 'sessions#create'
  #removes user_id from the session
  get '/logout', to: 'sessions#destroy'
  #form to create a new user
  get '/signup', to: 'users#new', as:'signup'
  #generates new user and adds to the database
  post '/signup', to: 'users#create'

  get '/search', to: 'sessions#search', as: 'search'

  get '/data', to: 'users#data', as:'data'

  resources :users do
    resources :children
    resources :availabilities
    resources :session_bookings
  end

  resources :schools do
    get '/users/:user_id', to: 'users#user_availabilities'
    get '/users/:user_id/bookings', to: 'users#user_bookings'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :minder_contracts, class_name: "Contract", foreign_key:"child_minder_id", dependent: :destroy
  has_many :parent_bosses, through: :minder_contracts, source: :parent, dependent: :destroy
  has_many :parent_contracts, class_name: "Contract", foreign_key:"parent_id", dependent: :destroy
  has_many :minders, through: :parent_contracts, source: :child_minder, dependent: :destroy
  has_many :children, dependent: :destroy
  has_many :postings, dependent: :destroy
  has_many :schools, through: :postings, dependent: :destroy
  has_many :session_bookings, dependent: :destroy
  has_many :availabilities, through: :session_bookings, dependent: :destroy
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, :length => { :minimum => 6}

  accepts_nested_attributes_for :children, reject_if: proc { |attributes| attributes['name'].blank? }


  # def password=(new_password)
  #   salt = BCrypt::Engine::generate_salt
  #   hashed = BCrypt::Engine::hash_secret(new_password, salt)
  #   self.password_digest = salt + hashed
  # end
  #
  # # authenticate(password: string) -> User?
  # def authenticate(password)
  #   # Salts generated by generate_salt are always 29 chars long.
  #   salt = password_digest[0..28]
  #   hashed = BCrypt::Engine::hash_secret(password, salt)
  #   return nil unless (salt + hashed) == self.password_digest
  # end
  #
  # def self.user_from_session
  #   User.find(session[:user_id])
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show, :destroy, :update]
  before_action :require_login, only: [:show, :edit, :update, :delete]
  before_action :authorize_user, only:[:show, :edit, :update, :delete]
  def show
    @children = @user.children
  end

  def edit
  end

  def data
    @children = Child.all
    @users = User.all
    @bookings = SessionBooking.all
   "/data"
  end

  def new
    if !user_logged_in
      @user = User.new
    else
      redirect_to '/'
    end
  end

  def user_availabilities
    @user = User.find(params[:user_id])
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      flash[:notice] = "Your account was created successfully, you can log in"
      redirect_to '/login'
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to '/signup'
    end
  end

  def update
    @user.update(user_params)
    @user.save
    redirect_to @user
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    flash[:notice] = "Account deleted"
    redirect_to '/'
  end

  private
  def set_user
      @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<div>
  <%= f.label :name %>
  <%= f.text_field :name %> <br>
  <%= f.label :email %>
  <%= f.text_field :email %> <br>
  <%= f.label :password %>
  <%= f.password_field :password %> <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %> <br>
</div> <br>

 <div id="add-children">
   <h3>Children</h3>
     <%= f.fields_for(:children) do |ff| %> <hr>
       <%= ff.label :name %>
       <%= ff.text_field :name %> <br>
       <%= ff.label :age %>
       <%= ff.number_field :age %> <br> <hr>
     <% end %> <br>

 </div>
 <%= f.submit %>
<% end %>

app/views/users/data.html.erb
<h1>Data</h1>
<h4>Children registered: <%= @children.all.length %></h4>
<h4>Users registered: <%= @users.all.length %></h4>
<h4>Total bookings: <%= @bookings.all.length %></h4>

app/views/users/edit.html.erb
<h1>Update</h1>
  <%= render 'form' %>
<%= link_to "Back to your details", @user%>

<%= form_tag user_path(@user.id), method: "delete" do %>
  <%= submit_tag "Delete Account" %>
<% end %>

app/views/users/new.html.erb
<div class="container text-center" style="width: 700px;">
        <h1 class="h3 mb-3 font-weight-normal">Create New User (Parent / Childminder)</h1> <br>
        <%= form_for :user, class: "form-group" do |f| %>
            <div class="row">
                <%= f.label :name, class:'col-sm h4 mb-1 font-weight-light' %>
                <%= f.text_field :name, class:'col-sm form-control' %><br>
            </div>
            <div class="row">
                <%= f.label :email, class:'col-sm h4 mb-1 font-weight-light' %>
                <%= f.email_field :email, class:'col-sm form-control' %> <br>
            </div>
            <div class="row">
              <%= f.label "Password", class:'col-sm h4 mb-1 font-weight-light' %>
              <%= f.password_field :password, class:'col-sm form-control' %> <br>
            </div>
            <div class="row">
                <%= f.label :password_confirmation, class:'col-sm h4 mb-1 font-weight-light' %>
                <%= f.password_field :password_confirmation, class:'col-sm form-control' %> <br>
            </div> <br>
         <br>
         <div class="row">
             <%= f.submit class:"btn btn-lg btn-dark btn-block"  %>
             <%= link_to "Cancel", '/', class:"btn btn-lg btn-outline-dark btn-block" %>
         </div>
        <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="card text-center">
    <div class="card-header">
      Your Profile
    </div>
    <div class="card-body">
      <h3 class="card-title"> <%= @user.name %> </h3>
      <p class="card-text">
        <hr>
        <span> <h5>Your children</h5> </span>

          <% @children.each do |child| %>
          <span>
          <%=link_to child.name, [@user,child] %>
          </span>
          <% end  %>
      </p>

      <div class="text-center col-sm-12">
        <a href="/users/<%="#{@user.id}"%>/children/new" class="btn btn-primary">New Child</a>
      </div>
      <hr>
      <span class="text-center col-sm-12">
      <%= link_to "Your Bookings", user_session_bookings_path(@user) %>
    </span>
      <%= link_to "Your Availabilities", user_availabilities_path(@user) %>
    </div>
    <div class="card-footer text-muted">

    </div>
  </div>
</div>