config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #homepage
  get '/', to: 'sessions#index', as: 'root'
  #login form
  get '/login', to: 'sessions#new', as:'login'
  #adds user_id to the session
  post '/', to: 'sessions#create'
  #removes user_id from the session
  get '/logout', to: 'sessions#destroy'
  #form to create a new user
  get '/signup', to: 'users#new', as:'signup'
  #generates new user and adds to the database
  post '/signup', to: 'users#create'

  get '/search', to: 'sessions#search', as: 'search'

  get '/data', to: 'users#data', as:'data'

  resources :users do
    resources :children
    resources :availabilities
    resources :session_bookings
  end

  resources :schools do
    get '/users/:user_id', to: 'users#user_availabilities'
    get '/users/:user_id/bookings', to: 'users#user_bookings'
  end
end

app/models/session_booking.rb
class SessionBooking < ApplicationRecord
  belongs_to :availability
  belongs_to :user
  belongs_to :child
end

app/controllers/session_bookings_controller.rb
class SessionBookingsController < ApplicationController

  before_action :set_booking, only: [:show, :destroy, :edit, :update]
  before_action :require_login, only: [:index, :show, :new, :create, :destroy]
  before_action :authorize_user_objects, only:[:index, :show, :new, :create, :destroy]

  def index
    @bookings = SessionBooking.all.select do |session_booking|
      session_booking.user_id == current_user.id
    end
  end

  def show
    if @booking == nil
      flash[:notice] = "The parent and booking don't match"
      redirect_to "/"
    end
  end

  def new
    redirect_to '/'
  end

  def create
    availability = Availability.find(params[:availability_id].to_i)
    max_num_children = availability.number_of_children
    if params[:session_bookings][:children_ids].length - 1 <= max_num_children
      params[:session_bookings][:children_ids].each do |child_id|
        if child_id != ""
          booking = SessionBooking.new(user_id: params[:user_id], availability_id: params[:availability_id], child_id: child_id)
          max_num_children -= 1
          if(booking.valid?)
            availability.update(number_of_children: max_num_children)
            booking.save
          end
        end
      end
      flash[:notice] = "#{SessionBooking.last.child.name} has been booked with #{SessionBooking.last.availability.user.name} on #{SessionBooking.last.availability.time_from.strftime("%A, %d %B")}"
      redirect_to user_session_bookings_path
    else
      flash[:notice] = "There is not enough spaces"
      redirect_to user_availability_path(availability.user.id, availability.id)
    end
  end

  def destroy
    a = Availability.find(@booking.availability_id)
    num_children = a.number_of_children
    a.update(:number_of_children => num_children + 1)
    @booking.destroy
    flash[:notice] = "Booking cancelled"
    redirect_to user_session_bookings_path
  end

  private

  def set_booking
    booking = SessionBooking.find(params[:id])
    if(booking.user_id == current_user.id)
      @booking = booking
    else
      redirect_to '/'
    end
  end

  def session_booking_params
    params.require(:session_booking).permit(:children_ids => [])
  end

end

app/views/session_bookings/index.html.erb
<div class="container">

  <hr>
  <div class="row text-center">
    <h1 class="col-sm h4 mb-1 font-weight-light">Your Bookings</h1>
  </div>
  <hr>

  <div class="container-fluid">
    <div class="row">
      <% @bookings.each do | booking | %>
        <div class="card-group col-sm-4 mb-2 mt-2">
          <div class="card text-center" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">
                <%= booking.availability.time_from.strftime("%A, %d %B") %>
              </h5>
              <p class="card-text">
                <medium>Booking For Child:</medium><br>
                <small>
                  <%= booking.child.name %>
                </small><br>
                <medium>with Child Minder:</medium><br>
                <small>
                  <% if(booking.availability.posting) %>
                    <%= booking.availability.posting.user.name %>
                  <% end %>
                </small>
              </p>
              <hr>
              <%= link_to "View", user_session_booking_path(current_user, booking), class:"btn btn-dark" %>
              <%= button_to "Cancel", user_session_booking_path(current_user, booking), :method => "delete", class:"btn btn-dark" %>
              <hr>
              <p class="card-text">
                <small class="text-muted">Booking ID:
                  <%= booking.id %>
                </small>
              </p>
            </div>
          </div>
        </div>
      <%  end %>
    </div>

  </div>
  <% #Calendar %>


  </div>

app/views/session_bookings/show.html.erb
<div class="container text-center">
  <hr>
  <div class="row text-center">
    <h1 class="col-sm h4 mb-1 font-weight-light">Viewing Booking ID:
      <%= @booking.id %></h1>
  </div>
  <hr>

<div class="row">
      <div class="card col-12">
        <div class="card-body">
          <h5 class="card-title">
            <%= @booking.availability.time_from.strftime("%A, %d %B") %>
          </h5>
          <p class="card-text">
            <medium>Booking For Child:</medium><br>
            <small>
              <%= @booking.child.name %>
            </small><br>
            <medium>with Child Minder:</medium><br>
            <small>
              <% if(@booking.availability.posting) %>
                <%= @booking.availability.posting.user.name %>:
                <%= @booking.availability.posting.user.email %>
              <% end %>
            </small>
          </p>
          <hr>
          <%= button_to "Cancel", user_session_booking_path(current_user, @booking), :method => "delete", class:"btn btn-dark" %>
            <br><span><%= link_to "Go Back", "/users/#{current_user.id}/session_bookings" %> </span>
          <hr>
        </div>
    </div>
  </div>
</div>