config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #homepage
  get '/', to: 'sessions#index', as: 'root'
  #login form
  get '/login', to: 'sessions#new', as:'login'
  #adds user_id to the session
  post '/', to: 'sessions#create'
  #removes user_id from the session
  get '/logout', to: 'sessions#destroy'
  #form to create a new user
  get '/signup', to: 'users#new', as:'signup'
  #generates new user and adds to the database
  post '/signup', to: 'users#create'

  get '/search', to: 'sessions#search', as: 'search'

  get '/data', to: 'users#data', as:'data'

  resources :users do
    resources :children
    resources :availabilities
    resources :session_bookings
  end

  resources :schools do
    get '/users/:user_id', to: 'users#user_availabilities'
    get '/users/:user_id/bookings', to: 'users#user_bookings'
  end
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :posting
  has_many :session_bookings, dependent: :destroy
  has_many :users, through: :session_bookings, dependent: :destroy
  validates :time_from, presence: true
  validates :time_until, presence: true
  validates :number_of_children, presence: true


  def school_id=(school_id)
    @school_id = school_id
  end

  def school_id
    @school_id
  end

  def user_id=(user_id)
    @user_id
  end

  def user_id
    @user_id
  end

  def start_time
    time_from
  end

  def end_time
    time_until
  end

  def user
    if(self.posting && self.posting.user_id)
      user = User.find(self.posting.user_id)
    else
      nil
    end
  end

end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  before_action :set_availability, only: [ :show, :update, :edit, :destroy, :booking]
  before_action :authorize_user_objects, only: [:show, :update, :edit, :delete, :booking, :create, :new]

  def index
    @available_dates = Availability.all.select do |availability|
        availability.user.id == current_user.id
    end
  end

  def show
    if @availability == nil
      flash[:notice] = "The childminder and availability don't match"
      redirect_to '/'
    end
    if @availability.session_bookings
      @bookings = @availability.session_bookings
    end
  end

  def edit
  end

  def update
    @availability.update(availability_params)
    @availability.save
    flash[:notice] = "Availability was updated"
    redirect_to user_availability_url(@availability)
  end

  def new
    @availability = Availability.new
  end

  def create
    if params[:availability][:time_from] == "" || params[:availability][:time_until] == ""
      @availability = Availability.new
      flash[:notice] = "Please enter correct times"
      return redirect_to new_user_availability_url(current_user)
    end
    availability = Availability.new(availability_params)
      posting = Posting.find_or_initialize_by(user_id: params[:user_id], school_id: params[:availability][:school_id])
      posting.availabilities << availability
      posting.save
      availability.posting = posting
      if availability.time_from < Time.now || availability.time_from > availability.time_until
        flash[:notice] = "Time can not be in the past"
        return redirect_to new_user_availability_url(current_user)
      end
      if availability.valid?
        availability.save
        flash[:notice] = "New availability was created"
        redirect_to user_availabilities_url(availability.user.id)
      else
        flash[:errors] = availability.errors.full_messages
        redirect_to new_user_availability_url(current_user)
      end
  end

  def destroy
    @availability.destroy
    redirect_to user_availabilities_path(current_user.id)
  end

  private
  def availability_params

    date_array = params[:date].values.map {|v| v.to_i}
    params[:availability][:time_from] = Time.new(date_array[2], date_array[1], date_array[0], params[:availability][:time_from].to_time.hour, params[:availability][:time_from].to_time.min)
    params[:availability][:time_until] = Time.new(date_array[2], date_array[1], date_array[0], params[:availability][:time_until].to_time.hour, params[:availability][:time_until].to_time.min)
    params.require(:availability).permit(:time_until, :time_from, :number_of_children, :cost_per_hour)
  end

  def set_availability
    availability = Availability.find(params[:id])
    if(availability.user.id == current_user.id)
      @availability = availability
    else
      nil
    end
  end

end

app/views/availabilities/_form.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-sm-12">
      <div class="card m-1">
        <div class="card-header">
          New Childminder Session
        </div>
        <div class="card-body text-center>
          <p class="card-text">
          <%=form_for [:user, @availability] do |f| %>
          <div class="form-group">
            <%= f.label "Date:" %>
              <%= date_select("date", "preferred_date", order: [:day, :month, :year], :discard_year => true, :default => Date.today) %>
          </div>
          <div class="form-group">
            <%= f.label "Session Time From:" %>
            <%= f.time_field :time_from %>
          </div>

          <div class="form-group">
          <%= f.label "Session Time To:" %>
          <%= f.time_field :time_until %>
          </div>

          <div class="form-group">
            <%= f.label "Max Slots Available:" %>
            <%= f.number_field :number_of_children %>
          </div>

          <div class="form-group">
            <%= f.label "Max Slots Available:" %>
            <%= f.collection_select :school_id, School.all, :id, :name %>
          </div>
          </p>
          <span>
          <%= f.submit class:"btn btn-primary"  %>
        </span>
        </div>
      <% end %>
      <p class="card-text">
      </p>
    </div>
  </div>
</div>
</div>

app/views/availabilities/edit.html.erb
<%= render "form" %>
<%= form_tag user_availability_path(@availability.user.id), method: "delete" do %>
  <%= submit_tag "Delete Availability" %>
<% end %>

app/views/availabilities/index.html.erb
<h1> Availabilities </h1>

<% if current_user.id == params[:id] %>
  <h3><%=link_to "Add a new availability", new_user_availability_path %><br></h3>
<% end %>

<%= month_calendar events: @available_dates do |date, a| %>
  <%= date %>
  <% a.each do |availability| %>
    <div>
      <p>Available places <%= availability.number_of_children %></p>
      <p>Booked places <%= availability.session_bookings.length %></p>
      <%= link_to "View", user_availability_path(current_user, availability) %></p>
    </div>
  <% end %>
<% end %>

app/views/availabilities/new.html.erb
<%= render "form" %>

app/views/availabilities/show.html.erb
<h1> This availablity </h1>
<p>Childminder: <%= @availability.user.name %></p>
<p>Contact: <%= @availability.user.email %></p>
<p>From<%= @availability.time_from %></p>
<p>Until<%= @availability.time_until %></p>
<p>Available places <%= @availability.number_of_children %></p>

<h3> Children booked for this availability</h3>
<%= @availability.session_bookings.length %>
<ol>
  <% @bookings.each do |booking| %>
    <h5><%= booking.child.name  %><h5>
      <span>Parent: <%=booking.child.user.name %></span><br>
      <span>Contact: <%=booking.child.user.email %></span>
  <% end %>
</ol>


<% if current_user.id == @availability.user.id %>
  <%= link_to "Update Availability", edit_user_availability_path(current_user.id) %><br>
<% end %>
<%= link_to "All availabilities for #{@availability.user.name}", user_availabilities_path(@availability.user.id) %><br>

<%= link_to "Go Back", "/" %>